export const DICTIONARY = {
  // 客户群体条件规则名
  ruleNameTargetUserCondition: [
    {
      id: '618b1eddc493c8e16e84967b',
      key: 'USER_TYPE',
      type: 'ruleNameTargetUserCondition',
      isEnable: 1,
      sort: 3,
      textEn: 'User type',
      textZhHans: '用户类型',
      textZhHant: '用戶類型',
      describe: '客户群体条件规则名',
      name: '客户群体条件规则名',
      value: '用户类型',
      disabled: false
    },
    {
      id: '618b1eddc493c8e16e84967f',
      key: 'PROMO_CODE',
      type: 'ruleNameTargetUserCondition',
      isEnable: 1,
      sort: 2,
      textEn: 'Promotion code',
      textZhHans: '参与优惠码',
      textZhHant: '參與優惠碼',
      describe: '客户群体条件规则名',
      name: '客户群体条件规则名',
      value: '参与优惠码',
      disabled: false
    },
    {
      id: '618b1eddc493c8e16e849684',
      key: 'REFERRAL_CODE',
      type: 'ruleNameTargetUserCondition',
      isEnable: 1,
      sort: 1,
      textEn: 'Referral code',
      textZhHans: '参与推广号',
      textZhHant: '參與推廣號',
      describe: '客户群体条件规则名',
      name: '客户群体条件规则名',
      value: '参与推广号',
      disabled: false
    }
  ],
  // 生效条件规则名
  ruleNameEffectiveCondition: [
    {
      id: '618b1eddc493c8e16e849639',
      key: 'REG_TIME',
      type: 'ruleNameEffectiveCondition',
      isEnable: 1,
      sort: 10,
      textEn: 'Registration time',
      textZhHans: '注册时间',
      textZhHant: '註冊時間',
      describe: '生效条件规则名',
      name: '生效条件规则名',
      value: '注册时间'
    },
    {
      id: '618b1eddc493c8e16e84963e',
      key: 'TRADE_COUNT',
      type: 'ruleNameEffectiveCondition',
      isEnable: 1,
      sort: 9,
      textEn: 'Trade count',
      textZhHans: '交易次数',
      textZhHant: '交易次數',
      describe: '生效条件规则名',
      name: '生效条件规则名',
      value: '交易次数'
    },
    {
      id: '618b1eddc493c8e16e849641',
      key: 'TRADE_TIME',
      type: 'ruleNameEffectiveCondition',
      isEnable: 1,
      sort: 8,
      textEn: 'Trade time',
      textZhHans: '交易时间',
      textZhHant: '交易時間',
      describe: '生效条件规则名',
      name: '生效条件规则名',
      value: '交易时间'
    },
    {
      id: '618b1eddc493c8e16e849647',
      key: 'OPEN_ACCOUNT_TIME',
      type: 'ruleNameEffectiveCondition',
      isEnable: 1,
      sort: 7,
      textEn: 'Account opening time',
      textZhHans: '开户时间',
      textZhHant: '開戶時間',
      describe: '生效条件规则名',
      name: '生效条件规则名',
      value: '开户时间'
    },
    {
      id: '618b1eddc493c8e16e849655',
      key: 'FIRST_DEPOSIT',
      type: 'ruleNameEffectiveCondition',
      isEnable: 1,
      sort: 6,
      textEn: 'First deposit amount',
      textZhHans: '首次入金',
      textZhHant: '首次入金',
      describe: '生效条件规则名',
      name: '生效条件规则名',
      value: '首次入金'
    },
    {
      id: '618b1eddc493c8e16e849656',
      key: 'INVITEE_FIRST_DEPOSIT',
      type: 'ruleNameEffectiveCondition',
      isEnable: 1,
      sort: 5,
      textEn: 'Invitee first deposit amount',
      textZhHans: '受邀人首次入金',
      textZhHant: '受邀人首次入金',
      describe: '生效条件规则名',
      name: '生效条件规则名',
      value: '受邀人首次入金'
    },
    {
      id: '618b1eddc493c8e16e849664',
      key: 'OPEN_SECURITIES_ACCOUNT_TIME',
      type: 'ruleNameEffectiveCondition',
      isEnable: 1,
      sort: 4,
      textEn: 'Securities account opening time',
      textZhHans: '证券户开立时间',
      textZhHant: '證券戶開立時間',
      describe: '生效条件规则名',
      name: '生效条件规则名',
      value: '证券户开立时间'
    },
    {
      id: '618b1eddc493c8e16e849665',
      key: 'DEPOSIT',
      type: 'ruleNameEffectiveCondition',
      isEnable: 1,
      sort: 3,
      textEn: 'Deposit amount',
      textZhHans: '单笔入金',
      textZhHant: '單筆入金',
      describe: '生效条件规则名',
      name: '生效条件规则名',
      value: '单笔入金'
    },
    {
      id: '618b1eddc493c8e16e84966e',
      key: 'FIRST_DEPOSIT_TIME',
      type: 'ruleNameEffectiveCondition',
      isEnable: 1,
      sort: 2,
      textEn: 'First deposit time',
      textZhHans: '首次入金时间',
      textZhHant: '首次入金時間',
      describe: '生效条件规则名',
      name: '生效条件规则名',
      value: '首次入金时间'
    },
    {
      id: '618b1eddc493c8e16e84967a',
      key: 'WITHDRAWAL_INTERVAL',
      type: 'ruleNameEffectiveCondition',
      isEnable: 1,
      sort: 1,
      textEn: 'Withdrawal interval',
      textZhHans: '出金间隔时间',
      textZhHant: '出金間隔時間',
      describe: '生效条件规则名',
      name: '生效条件规则名',
      value: '出金间隔时间'
    }
  ],
  // 派发条件规则名
  ruleNameDistributeCondition: [
    {
      id: '618b1eddc493c8e16e849621',
      key: 'IS_USER_TRIGGER',
      type: 'ruleNameDistributeCondition',
      isEnable: 1,
      sort: 3,
      textEn: 'Is triggerred by user',
      textZhHans: '是否用户触发',
      textZhHant: '是否用戶觸發',
      describe: '派发条件规则名',
      name: '派发条件规则名',
      value: '是否用户触发',
      disabled: false
    },
    {
      id: '618b1eddc493c8e16e849622',
      key: 'COUPON_COUNT',
      type: 'ruleNameDistributeCondition',
      isEnable: 1,
      sort: 2,
      textEn: 'Total distribute coupon count',
      textZhHans: '派发卡券总数量',
      textZhHant: '派發卡券總數量',
      describe: '派发条件规则名',
      name: '派发条件规则名',
      value: '派发卡券总数量',
      disabled: false
    },
    {
      id: '618b1eddc493c8e16e84962c',
      key: 'DAY_COUPON_COUNT',
      type: 'ruleNameDistributeCondition',
      isEnable: 1,
      sort: 1,
      textEn: 'Daily distribute coupon count',
      textZhHans: '每日派发卡券数量',
      textZhHant: '每日派發卡券數量',
      describe: '派发条件规则名',
      name: '派发条件规则名',
      value: '每日派发卡券数量',
      disabled: false
    }
  ],
  // 市场类型
  tradeMarketType: [
    {
      id: '612da30ec493c8e16e00565c',
      key: 'XHKF',
      type: 'tradeMarketType',
      isEnable: 1,
      sort: 0,
      textEn: 'HK Futures Exchange(HKFE)',
      textZhHans: '港期',
      textZhHant: '港期',
      describe: '交易市场类型',
      name: '交易市场类型',
      value: '港期'
    },
    {
      id: '612da30ec493c8e16e00566d',
      key: 'HK',
      type: 'tradeMarketType',
      isEnable: 1,
      sort: 0,
      textEn: 'HK Stocks',
      textZhHans: '港股',
      textZhHant: '港股',
      describe: '交易市场类型',
      name: '交易市场类型',
      value: '港股'
    },
    {
      id: '612da30ec493c8e16e00566e',
      key: 'XCBT',
      type: 'tradeMarketType',
      isEnable: 1,
      sort: 0,
      textEn: 'Chicago Board of Trade(CBOT)',
      textZhHans: '芝交所期货',
      textZhHant: '芝交所期貨',
      describe: '交易市场类型',
      name: '交易市场类型',
      value: '芝交所期货'
    },
    {
      id: '612da30ec493c8e16e00566f',
      key: 'US',
      type: 'tradeMarketType',
      isEnable: 1,
      sort: 0,
      textEn: 'US Stocks',
      textZhHans: '美股',
      textZhHant: '美股',
      describe: '交易市场类型',
      name: '交易市场类型',
      value: '美股'
    },
    {
      id: '612da30ec493c8e16e00567c',
      key: 'XCME',
      type: 'tradeMarketType',
      isEnable: 1,
      sort: 0,
      textEn: 'Chicago Mercantile Exchange(CME)',
      textZhHans: '芝交所商业',
      textZhHant: '芝交所商業',
      describe: '交易市场类型',
      name: '交易市场类型',
      value: '芝交所商业'
    },
    {
      id: '612da30ec493c8e16e00567d',
      key: 'XCEC',
      type: 'tradeMarketType',
      isEnable: 1,
      sort: 0,
      textEn: 'New York Commerce Exchange(COMEX)',
      textZhHans: '纽交所期货',
      textZhHant: '紐交所期貨',
      describe: '交易市场类型',
      name: '交易市场类型',
      value: '纽交所期货'
    },
    {
      id: '612da30ec493c8e16e00568b',
      key: 'XNYM',
      type: 'tradeMarketType',
      isEnable: 1,
      sort: 0,
      textEn: 'New York Mercantile Exchange(NYMEX)',
      textZhHans: '纽交所商业',
      textZhHant: '紐交所商業',
      describe: '交易市场类型',
      name: '交易市场类型',
      value: '纽交所商业'
    },
    {
      id: '612da30ec493c8e16e00568e',
      key: 'XSES',
      type: 'tradeMarketType',
      isEnable: 1,
      sort: 0,
      textEn: 'Singapore Exchange(SGX)',
      textZhHans: '新交所期货',
      textZhHant: '新交所期貨',
      describe: '交易市场类型',
      name: '交易市场类型',
      value: '新交所期货'
    }
  ],
  // 活动规则条件
  ruleCondition: [
    {
      id: '618b1eddc493c8e16e8496b6',
      key: 'BETWEEN',
      type: 'ruleCondition',
      isEnable: 1,
      sort: 9,
      textEn: 'between',
      textZhHans: '区间在',
      textZhHant: '區間在',
      describe: '活动规则条件',
      name: '活动规则条件',
      value: '区间在'
    },
    {
      id: '618b1eddc493c8e16e8496af',
      key: 'LTE',
      type: 'ruleCondition',
      isEnable: 1,
      sort: 8,
      textEn: 'less than and equal',
      textZhHans: '小于等于',
      textZhHant: '小於等於',
      describe: '活动规则条件',
      name: '活动规则条件',
      value: '小于等于'
    },
    {
      id: '618b1eddc493c8e16e8496ac',
      key: 'GTE',
      type: 'ruleCondition',
      isEnable: 1,
      sort: 7,
      textEn: 'greater than and equal',
      textZhHans: '大于等于',
      textZhHant: '大於等於',
      describe: '活动规则条件',
      name: '活动规则条件',
      value: '大于等于'
    },
    {
      id: '618b1eddc493c8e16e8496a7',
      key: 'LT',
      type: 'ruleCondition',
      isEnable: 1,
      sort: 6,
      textEn: 'less than',
      textZhHans: '小于',
      textZhHant: '小於',
      describe: '活动规则条件',
      name: '活动规则条件',
      value: '小于'
    },
    {
      id: '618b1eddc493c8e16e8496a2',
      key: 'GT',
      type: 'ruleCondition',
      isEnable: 1,
      sort: 5,
      textEn: 'greater than',
      textZhHans: '大于',
      textZhHant: '大於',
      describe: '活动规则条件',
      name: '活动规则条件',
      value: '大于'
    },
    {
      id: '618b1eddc493c8e16e84969a',
      key: 'NIN',
      type: 'ruleCondition',
      isEnable: 1,
      sort: 4,
      textEn: 'include',
      textZhHans: '不包含',
      textZhHant: '不包含',
      describe: '活动规则条件',
      name: '活动规则条件',
      value: '不包含'
    },
    {
      id: '618b1eddc493c8e16e849697',
      key: 'IN',
      type: 'ruleCondition',
      isEnable: 1,
      sort: 3,
      textEn: 'include',
      textZhHans: '包含',
      textZhHant: '包含',
      describe: '活动规则条件',
      name: '活动规则条件',
      value: '包含'
    },
    {
      id: '618b1eddc493c8e16e84968f',
      key: 'NE',
      type: 'ruleCondition',
      isEnable: 1,
      sort: 2,
      textEn: 'not equal',
      textZhHans: '不等于',
      textZhHant: '不等於',
      describe: '活动规则条件',
      name: '活动规则条件',
      value: '不等于'
    },
    {
      id: '618b1eddc493c8e16e84968b',
      key: 'EQ',
      type: 'ruleCondition',
      isEnable: 1,
      sort: 1,
      textEn: 'equal',
      textZhHans: '等于',
      textZhHant: '等於',
      describe: '活动规则条件',
      name: '活动规则条件',
      value: '等于'
    }
  ]
}
